__version__ = "1.0.8"
__title__ = "mongolian-bank-exchange-rate"
__description__ = "Mongolian Bank Exchange Rate API"
__author__ = "Battseren Badral"
__author_email__ = "bbattseren88@gmail.com"
__url__ = "https://github.com/btseee/mongolian-bank-exchange-rate"
__license__ = "MIT"
__donation__ = "https://buymeacoffee.com/btseee"
